CREATE DATABASE BD_SYSREL;
USE BD_SYSREL;

CREATE TABLE TB_TELAS (
ID INT PRIMARY KEY AUTO_INCREMENT,
DESCRICAO VARCHAR(50) NOT NULL,
CAMINHO VARCHAR(100) NULL
);

CREATE TABLE TB_PERMISSAO_TELAS (
ID_TELA_FK INT PRIMARY KEY AUTO_INCREMENT,
ADM BIT,
LIDER BIT
);

ALTER TABLE TB_PERMISSAO_TELAS ADD CONSTRAINT FK_TB_TELAS FOREIGN KEY (ID_TELA_FK) REFERENCES TB_TELAS(ID);

CREATE TABLE TB_LIDER_PESQUISA (
ID INT PRIMARY KEY AUTO_INCREMENT,
NOME VARCHAR(80) NOT NULL,
PRONTUARIO VARCHAR(12) NOT NULL,
EMAIL VARCHAR(45) NOT NULL,
SENHA VARCHAR(64) NOT NULL,
SENHA_ANTIGA VARCHAR(64) NULL
);

CREATE TABLE TB_ADMINISTRADOR (
ID INT PRIMARY KEY AUTO_INCREMENT,
EMAIL VARCHAR(45) NOT NULL,
SENHA VARCHAR(64) NOT NULL,
SENHA_ANTIGA VARCHAR(64) NULL
)
